name: Test
on:
  push:
    branches:
      - 'master'
jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Select Xcode 16.2
        run: sudo xcode-select -switch /Applications/Xcode_16.2.app

      - name: Unit tests
        run: fastlane unit_test

      - name: UI tests
        run: fastlane ui_test
      
      - name: Code coverage
        run: fastlane coverage